### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by mubix** [metasploit/resource-portal-data#2]
Might think about adding a "Books" section to include titles, authors and importantly dates of publish of books that give good Metasploit info

**Comment by todb-r7** [comment]
I'll dream up a book resource today. I'm thinking Metasploit Unleashed. It's a fine document and still relevant, though not enough pages on Aux modules. :)

**Comment by todb-r7** [comment]
[This PR](https://github.com/todb-r7/resource-portal-data/issues/1) was aimed at my own fork by accident, do'h. #5 is correct.
